SUPABASE_URL = "https://csckgnovnktmuguacoia.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzY2tnbm92bmt0bXVndWFjb2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NTY5ODYsImV4cCI6MjA3NzEzMjk4Nn0.YCJoD7c_H-iP8SqZd0rbsh3NAJe8sjGpkzrjDFSWYkg"
SUPABASE_BUCKET = "calligraphy"
